### ISSUE TITLE
Switch to New user is slow as it returns CURLE_RECV_ERROR first and wait at there

### ISSUE THREAD

**Issue by maowenzhang** [launchdarkly/c-client-sdk#25]
**Describe the bug**
It's slow when we switch to new user by LDClientIdentify. 
Refer to below image, it returns CURLE_RECV_ERROR and don't retry right way, but wait for a while. 
![image](https://user-images.githubusercontent.com/1454209/59839326-0bd4b900-9383-11e9-998d-f539d2322859.png)

2nd, If fail once, and then successed, the retries won't be set to zero, so if failed several times, it will wait for very long time, even it had success before. 
![image](https://user-images.githubusercontent.com/1454209/59839863-eac09800-9383-11e9-94e2-a4e4b938c67b.png)

**To reproduce**
Steps to reproduce the behavior.
Use codes as below, need use specific keys. 
```
	LDConfig* config = LDConfigNew("xxx");
	
	// First User
	LDUser* user = LDUserNew("xxx"); 
	LDClient* client = LDClient::Init(config, user, 10000);
	LDClient_i* client_i = LDClientGet();
	// wait for init finish
	
	// Switch User
	// 
	std::string userKey = "yyy";
	LDUser* newuser = LDUserNew(userKey.c_str());
	LDClientIdentify(client_i, newuser);
```

**Expected behavior**

1. It would be best to get it without this error: CURLE_RECV_ERROR. 
2. If has this error, then retry immediatly intead of waiting at there for next time. 
3. If fail to init --> success (the 'retires' should be reset to 0), and no need to wait too long when fail next time. 

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
The version of this SDK that you are using.

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

**Additional context**

1. If diable streaming and use poller instead, it works well without any failure and able to get flags quickly. 
2. If add below codes to retry when meet this error "CURLE_RECV_ERROR ", it works well and able to init success right after first failure (when switch user). 
![image](https://user-images.githubusercontent.com/1454209/59840316-ae416c00-9384-11e9-81ba-9381b0b7b96e.png)

**Comment by maowenzhang** [comment]
This is quite important for us, our application is a large c++ based application, and we have lots of feature flags reply on LD to finish initialization. 

If it fails and waits there (it could success later) for too long, then it impacts our features that depend on latest values.

**Comment by maowenzhang** [comment]
If it takes much time to fix, what about disabling streaming and use poller instead. The comment says poller is not recommended, will there be any issue if using poller instead of streaming?  Thanks!

**Comment by maowenzhang** [comment]
It returns the CURL_RECV_ERROR when doing streaming, because switch user calls below codes to shutdown socket.  So in this case, I think we should start and read stream right aways instead of wating at there. 

![image](https://user-images.githubusercontent.com/1454209/59895928-0d50c080-9419-11e9-84ca-e54c43f96321.png)

**Comment by hroederld** [comment]
Hello @maowenzhang thank you for your very detailed bug report!

We released a patch today https://github.com/launchdarkly/c-client-sdk/releases/tag/1.3.2 that should solve your issue.

**Comment by maowenzhang** [comment]
Great @hroederld ! Thanks for addressing it quickly!

**Comment by hroederld** [comment]
Hi @maowenzhang 

I'm going to close this issue now as it seems to be resolved. If you have any more problems feel free to submit them.

Thanks!
