### ISSUE TITLE
2.1.0 OSX Dynamic release is missing .so files

### ISSUE THREAD

**Issue by mstrater** [launchdarkly/c-client-sdk#57]
I'm not very familiar with Mac infrastructure, but I believe the dynamic library is supposed to have .so files rather than the .a file. I don't think any of the 2.1.0 Mac releases contain them.

**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
The version of this SDK that you are using.

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

**Additional context**

**Comment by hroederld** [comment]
Hello @mstrater 

We switched build systems in `2.x`, and looks like that was botched in the process. I'm not sure at the moment if it is simply incorrectly labeled, or actually a static library, but we will investigate and get a new release out soon. It will be released with the `.dylib` extension.

Thanks!

**Comment by mstrater** [comment]
Have you had a chance to investigate the issue?

**Comment by hroederld** [comment]
Hi @mstrater 

Sorry I missed your follow up. We have found the issue but have not merged an update yet.

Expect a release this week.

Thanks!

**Comment by bwoskow-ld** [comment]
This is fixed in [version 2.1.1](https://github.com/launchdarkly/c-client-sdk/releases/tag/2.1.1).

**Comment by mstrater** [comment]
Awesome! Thanks!
